services:
  catalogdb:
    image: postgres
  basketdb:
    image: postgres
  distributedcache:
    image: redis

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: src
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: src
      dockerfile: Services/Basket/Basket.Api/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket: